// ============================================
// lang.js — نظام اللغات الثلاث
// Guide de survie ENSTP
// ============================================

const LANG_DATA = {
  fr: {
    // ============ عام ============
    appName: "Guide de survie ENSTP",
    tagline: "Ton premier jour, dans ta poche.",
    back: "← Retour",
    home: "🏠 Accueil",
    search: "🔎 Chercher…",
    noResult: "Aucun résultat",
    tryOther: "Essayez un autre mot",
    suggestions: "💡 Essayez :",
    viewMap: "📍 Voir sur Maps",
    viewVideo: "🎥 Voir la vidéo",
    comingSoon: "Bientôt disponible",
    toComplete: "À compléter",
    qrTitle: "📱 QR Code",
    qrScan: "Scannez ce QR code",
    close: "Fermer",
    loading: "Chargement…",
    
    // ============ الصفحة الرئيسية ============
    welcomeTitle: "Bienvenue",
    welcomeSubtitle: "Tout ce dont tu as besoin pour ton premier jour à l'ENSTP.",
    startBtn: "ابدأ",
    installBtn: "Installer l'app",
    
    // ============ الأقسام ============
    sectionEcole: "Mon école",
    sectionProfs: "Mes enseignants",
    sectionAdmin: "Mon administration",
    sectionServices: "Services",
    sectionShopping: "Achats & restauration",
    sectionTransport: "Transport",
    sectionCite: "Cité universitaire",
    sectionNatation: "Natation à Alger",
    sectionSport: "Sport",
    sectionGreen: "Projet vert",
    sectionPodcast: "Podcast étudiant",
    sectionCourses: "Formations",
    sectionAbout: "Qui sommes-nous",
    sectionMap: "Plan de l'école",
    
    // ============ 1. مدرستي ============
    ecoleIntro: "Tous les lieux de l'école : salles, amphis, labos, services.",
    ecoleSalle: "Où est ma salle ?",
    ecoleSalleDesc: "26 salles de TD numérotées de 1 à 26, réparties sur plusieurs étages.",
    ecoleAmphi: "Amphithéâtres A et B",
    ecoleAmphiDesc: "Deux grands amphithéâtres pour les cours magistraux.",
    ecoleResto: "Restaurant universitaire",
    ecoleRestoDesc: "Repas à tarif étudiant, 3 fois par jour.",
    ecoleFoyer: "Foyer",
    ecoleFoyerDesc: "Espace de détente et de rencontre entre étudiants.",
    ecoleDept: "Départements",
    ecoleDeptPrep: "Cycle préparatoire",
    ecoleDeptMat: "Matériaux & Structures",
    ecoleDeptInf: "Infrastructures de Base",
    ecoleLabs: "Laboratoires",
    ecoleLabPhysique: "Laboratoire de Physique",
    ecoleLabChimie: "Laboratoire de Chimie",
    ecoleLabMeca: "Laboratoire de Mécanique des Fluides",
    ecoleLabElec: "Laboratoire d'Électricité",
    ecoleMedecin: "Médecin de l'école",
    ecoleMedecinDesc: "Infirmerie — premiers soins.",
    ecoleSécu: "Bureau de la sécurité sociale",
    ecoleSécuDesc: "Pour l'affiliation et les remboursements.",
    ecoleEntrepreneuriat: "Centre d'entrepreneuriat",
    ecoleEntrepreneuriatDesc: "Accompagnement pour créer ton propre projet.",
    ecoleBiblio: "Bibliothèque",
    ecoleBiblioDesc: "Salles de lecture et prêt de livres.",
    ecoleCite: "Centre de la cité universitaire",
    ecoleCiteDesc: "Gestion des résidences universitaires.",
    
    // ============ 2. أساتذتي ============
    profsIntro: "Recherche par matière ou par nom.",
    profPhysique: "Physique",
    profChimie: "Chimie",
    profAlgebre: "Algèbre",
    profAnalyse: "Analyse",
    profStats: "Statistiques",
    profFrancais: "Français",
    profAnglais: "Anglais",
    profEco: "Économie",
    profGestion: "Gestion",
    profInfo: "Informatique",
    
    // ============ 3. إدارتي ============
    adminIntro: "Bureaux administratifs et contacts.",
    adminDirection: "Direction",
    adminScolarite: "Scolarité",
    adminDept: "Secrétariat des départements",
    adminRH: "Ressources humaines",
    adminFinances: "Finances",
    
    // ============ 4. الخدمات ============
    servicesIntro: "Toutes les démarches administratives.",
    srvStage: "Convention de stage",
    srvStageDesc: "Démarches pour obtenir une convention de stage.",
    srvSecu: "Sécurité sociale",
    srvSecuDesc: "Inscription et suivi.",
    srvBiblio: "Adhésion à la bibliothèque",
    srvBiblioDesc: "Inscription gratuite avec carte étudiant + photo.",
    srvClub: "Rejoindre un club",
    srvClubDesc: "Sport, culture, art…",
    srvIqra: "Plateforme Iqra",
    srvIqraDesc: "Accès à la plateforme de lecture numérique.",
    srvAbsence: "Justificatif d'absence",
    srvAbsenceDesc: "Dépôt de document médical sous 3 jours.",
    srvCarte: "Carte d'étudiant",
    srvCarteDesc: "Délivrée après inscription définitive.",
    srvCartePerdue: "J'ai perdu ma carte",
    srvCartePerdueDesc: "Déclaration de perte + 2 photos.",
    srvAttestation: "Attestation de scolarité",
    srvAttestationDesc: "Demande écrite à la scolarité.",
    srvReleve: "Relevé de notes",
    srvReleveDesc: "Document officiel des notes.",
    srvProgress: "Voir mes notes sur Progress",
    srvProgressDesc: "Plateforme en ligne de l'école.",
    
    // ============ 5. التسوق والأكل ============
    shoppingIntro: "Manger, acheter, se soigner autour de l'école.",
    shopResto: "Restaurants",
    shopRestoDesc: "Autour de l'école.",
    shopCafe: "Cafés",
    shopCafeDesc: "Pour réviser ou se retrouver.",
    shopPrint: "Photocopie & impression",
    shopPrintDesc: "Imprimer cours et documents.",
    shopPharma: "Pharmacies",
    shopPharmaDesc: "De garde : demander à la pharmacie.",
    shopDocteur: "Médecins",
    shopDocteurDesc: "Généralistes et spécialistes.",
    shopSecu: "Sécurité sociale (CNAS)",
    shopSecuDesc: "Agence CNAS la plus proche.",
    shopBenOmar: "Ben Omar — Kouba",
    shopBenOmarDesc: "Centre commercial à Kouba.",
    shopTchof: "Centre Tchof",
    shopTchofDesc: "Espace commercial et de loisirs.",
    
    // ============ 6. النقل ============
    transportIntro: "Bus, taxis, métro, train, tram.",
    trBusUniv: "Bus universitaire",
    trBusUnivDesc: "Dessert les cités universitaires.",
    trBusPublic: "Bus public",
    trBusPublicDesc: "Lignes vers centre-ville, gare, métro.",
    trTaxi: "Taxis collectifs",
    trTaxiDesc: "\"Y'sir hitt nrouhou\" — tarif fixe par place.",
    trHeetch: "Heetch & VTC",
    trHeetchDesc: "Applications de VTC.",
    trMetro: "Métro d'Alger",
    trMetroDesc: "Station la plus proche de Kouba.",
    trTrain: "Train (SNTF)",
    trTrainDesc: "Gares principales.",
    trTram: "Tramway",
    trTramDesc: "Carte SITRAM gratuite pour étudiants.",
    trSitram: "Carte SITRAM (gratuite)",
    trSitramDesc: "Carte de transport gratuite pour étudiants.",
    trInterWilaya: "Transport entre wilayas",
    trInterWilayaDesc: "Bus et trains vers d'autres régions.",
    trGareRoutiere: "Gare routière (Kharouba)",
    trGareRoutiereDesc: "Départs vers les wilayas.",
    trAeroport: "Aéroport Houari Boumediene",
    trAeroportDesc: "Vols internationaux et nationaux.",
    trGareTrain: "Gare ferroviaire",
    trGareTrainDesc: "Lignes SNTF.",
    
    // ============ 7. الإقامة ============
    citeIntro: "Vie à la cité universitaire.",
    citeGaridi: "Résidence Garidi",
    citeGaridiDesc: "La plus proche de l'ENSTP.",
    citeSaid: "Résidence Saïd Hamdine",
    citeSaidDesc: "À quelques minutes de bus.",
    citeRouiba: "Résidence Rouiba",
    citeRouibaDesc: "Plus éloignée. Nécessite transport.",
    
    // ============ 8. السباحة ============
    natationIntro: "Où nager à Alger.",
    natPiscine: "Piscines",
    natPiscineDesc: "Piscines publiques et privées.",
    natPlage: "Plages",
    natPlageDesc: "Plages publiques.",
    natClub: "Clubs de natation",
    natClubDesc: "Clubs étudiants.",
    
    // ============ 9. الرياضة ============
    sportIntro: "Sport universitaire et hors campus.",
    sportUniv: "Sport universitaire",
    sportUnivDesc: "Activités proposées par l'ONSU.",
    sportHors: "Sport hors résidence",
    sportHorsDesc: "Salles et clubs privés.",
    sportFootball: "Football",
    sportFootballDesc: "Matchs libres.",
    sportRunning: "Running",
    sportRunningDesc: "Course à pied.",
    sportBasket: "Basket / Volley",
    sportBasketDesc: "Sports collectifs.",
    
    // ============ 10. الأخضر ============
    greenIntro: "Projet vert et recyclage.",
    greenRecy: "Recyclage du papier",
    greenRecyDesc: "Collecte de papier usagé.",
    greenEcologie: "Écologie",
    greenEcologieDesc: "Actions écologiques.",
    
    // ============ 11. بودكاست ============
    podcastIntro: "Podcast étudiant ENSTP.",
    podcastEp1: "Épisode 1",
    podcastEp1Desc: "Bienvenue à l'ENSTP.",
    podcastEp2: "Épisode 2",
    podcastEp2Desc: "Vie étudiante.",
    podcastEp3: "Épisode 3",
    podcastEp3Desc: "Conseils pour réussir.",
    
    // ============ 12. دورات ============
    coursesIntro: "Formations et cours.",
    courseMath: "Mathématiques",
    coursePhysique: "Physique",
    courseInfo: "Informatique",
    
    // ============ 13. من نحن ============
    aboutIntro: "Un projet étudiant, 100% gratuit.",
    aboutMission: "Notre mission",
    aboutMissionDesc: "Aider chaque nouvel étudiant à s'intégrer.",
    aboutTeam: "Notre équipe",
    aboutTeamDesc: "Étudiants de 1ère année Ingénieur, Groupe 2, Infrastructures de Base.",
    aboutValues: "Nos valeurs",
    aboutValuesDesc: "Entraide, gratuité, respect, transparence, confiance.",
    aboutJoin: "Rejoindre l'équipe",
    aboutJoinDesc: "Contacte-nous via le groupe officiel.",
    
    // ============ 14. Cartographie ============
    mapIntro: "Clique sur un lieu pour voir son nom.",
    mapPlaces: "Lieux"
  },
  
  ar: {
    // ============ عام ============
    appName: "دليل البقاء ENSTP",
    tagline: "يومك الأول، في جيبك.",
    back: "→ رجوع",
    home: "🏠 الرئيسية",
    search: "🔎 ابحث…",
    noResult: "لا توجد نتائج",
    tryOther: "جرّب كلمة أخرى",
    suggestions: "💡 جرّب:",
    viewMap: "📍 عرض على الخريطة",
    viewVideo: "🎥 مشاهدة الفيديو",
    comingSoon: "قريباً",
    toComplete: "يُكمل",
    qrTitle: "📱 رمز QR",
    qrScan: "امسح رمز QR",
    close: "إغلاق",
    loading: "جارٍ التحميل…",
    
    // ============ الصفحة الرئيسية ============
    welcomeTitle: "مرحباً",
    welcomeSubtitle: "كل ما تحتاجه ليومك الأول في المدرسة.",
    startBtn: "ابدأ",
    installBtn: "ثبّت التطبيق",
    
    // ============ الأقسام ============
    sectionEcole: "مدرستي",
    sectionProfs: "أساتذتي",
    sectionAdmin: "إدارتي",
    sectionServices: "الخدمات",
    sectionShopping: "التسوق والأكل",
    sectionTransport: "النقل",
    sectionCite: "الإقامة الجامعية",
    sectionNatation: "السباحة في الجزائر",
    sectionSport: "الرياضة",
    sectionGreen: "المشروع الأخضر",
    sectionPodcast: "بودكاست الطالب",
    sectionCourses: "دورات",
    sectionAbout: "من نحن",
    sectionMap: "خريطة المدرسة",
    
    // ============ 1. مدرستي ============
    ecoleIntro: "كل أماكن المدرسة: القاعات، المدرجات، المخابر، الخدمات.",
    ecoleSalle: "أين قاعتي؟",
    ecoleSalleDesc: "26 قاعة مرقّمة من 1 إلى 26، موزعة على عدة طوابق.",
    ecoleAmphi: "المدرجان A و B",
    ecoleAmphiDesc: "مدرجان كبيران للمحاضرات.",
    ecoleResto: "المطعم الجامعي",
    ecoleRestoDesc: "وجبات بسعر طلابي، 3 مرات يومياً.",
    ecoleFoyer: "الفوير",
    ecoleFoyerDesc: "فضاء للراحة واللقاء بين الطلاب.",
    ecoleDept: "الأقسام",
    ecoleDeptPrep: "القسم التحضيري",
    ecoleDeptMat: "المواد والهياكل",
    ecoleDeptInf: "المنشآت القاعدية",
    ecoleLabs: "المخابر",
    ecoleLabPhysique: "مخبر الفيزياء",
    ecoleLabChimie: "مخبر الكيمياء",
    ecoleLabMeca: "مخبر ميكانيك الموائع",
    ecoleLabElec: "مخبر الكهرباء",
    ecoleMedecin: "طبيب المدرسة",
    ecoleMedecinDesc: "العيادة — الإسعافات الأولية.",
    ecoleSécu: "مكتب الضمان الاجتماعي",
    ecoleSécuDesc: "للانتساب والتعويضات.",
    ecoleEntrepreneuriat: "مركز المقاولاتية",
    ecoleEntrepreneuriatDesc: "مرافقة لإنشاء مشروعك الخاص.",
    ecoleBiblio: "المكتبة",
    ecoleBiblioDesc: "قاعات القراءة واستعارة الكتب.",
    ecoleCite: "مركز الإقامة الجامعية",
    ecoleCiteDesc: "إدارة الإقامات الجامعية.",
    
    // ============ 2. أساتذتي ============
    profsIntro: "ابحث حسب المادة أو الاسم.",
    profPhysique: "الفيزياء",
    profChimie: "الكيمياء",
    profAlgebre: "الجبر",
    profAnalyse: "التحليل",
    profStats: "الإحصاء",
    profFrancais: "الفرنسية",
    profAnglais: "الإنجليزية",
    profEco: "الاقتصاد",
    profGestion: "التسيير",
    profInfo: "الإعلام الآلي",
    
    // ============ 3. إدارتي ============
    adminIntro: "المكاتب الإدارية وجهات الاتصال.",
    adminDirection: "الإدارة",
    adminScolarite: "الشؤون الطلابية",
    adminDept: "أمانة الأقسام",
    adminRH: "الموارد البشرية",
    adminFinances: "المالية",
    
    // ============ 4. الخدمات ============
    servicesIntro: "كل الإجراءات الإدارية.",
    srvStage: "اتفاقية التربص",
    srvStageDesc: "إجراءات الحصول على اتفاقية تربص.",
    srvSecu: "الضمان الاجتماعي",
    srvSecuDesc: "الانتساب والمتابعة.",
    srvBiblio: "الانضمام إلى المكتبة",
    srvBiblioDesc: "تسجيل مجاني ببطاقة الطالب + صورة.",
    srvClub: "الانضمام إلى نادٍ",
    srvClubDesc: "رياضة، ثقافة، فن…",
    srvIqra: "منصة اقرأ",
    srvIqraDesc: "الوصول إلى منصة القراءة الرقمية.",
    srvAbsence: "تبرير الغياب",
    srvAbsenceDesc: "تقديم وثيقة طبية خلال 3 أيام.",
    srvCarte: "بطاقة الطالب",
    srvCarteDesc: "تُسلَّم بعد التسجيل النهائي.",
    srvCartePerdue: "أضعت بطاقتي",
    srvCartePerdueDesc: "تصريح بالضياع + صورتان.",
    srvAttestation: "شهادة مدرسية",
    srvAttestationDesc: "طلب كتابي للشؤون الطلابية.",
    srvReleve: "كشف النقاط",
    srvReleveDesc: "وثيقة رسمية للنقاط.",
    srvProgress: "رؤية نقاطي في Progress",
    srvProgressDesc: "منصة المدرسة الإلكترونية.",
    
    // ============ 5. التسوق والأكل ============
    shoppingIntro: "الأكل، الشراء، العلاج حول المدرسة.",
    shopResto: "مطاعم",
    shopRestoDesc: "حول المدرسة.",
    shopCafe: "مقاهي",
    shopCafeDesc: "للمراجعة أو اللقاء.",
    shopPrint: "تصوير وطباعة",
    shopPrintDesc: "طباعة الدروس والوثائق.",
    shopPharma: "صيدليات",
    shopPharmaDesc: "المناوبة: اسأل الصيدلية.",
    shopDocteur: "أطباء",
    shopDocteurDesc: "عامون وأخصائيون.",
    shopSecu: "الضمان الاجتماعي (CNAS)",
    shopSecuDesc: "أقرب وكالة CNAS.",
    shopBenOmar: "بن عمر — القبة",
    shopBenOmarDesc: "مركز تجاري بالقبة.",
    shopTchof: "مركز تشوف",
    shopTchofDesc: "فضاء تجاري وترفيهي.",
    
    // ============ 6. النقل ============
    transportIntro: "حافلات، تكاسي، مترو، قطار، ترامواي.",
    trBusUniv: "النقل الجامعي",
    trBusUnivDesc: "يخدم الإقامات الجامعية.",
    trBusPublic: "النقل العمومي",
    trBusPublicDesc: "خطوط نحو وسط المدينة، المحطة، المترو.",
    trTaxi: "سيارات أجرة جماعية",
    trTaxiDesc: "\"يسير هيتش نروحو\" — سعر ثابت للمقعد.",
    trHeetch: "هيتش و VTC",
    trHeetchDesc: "تطبيقات النقل.",
    trMetro: "مترو الجزائر",
    trMetroDesc: "أقرب محطة من القبة.",
    trTrain: "القطار (SNTF)",
    trTrainDesc: "المحطات الرئيسية.",
    trTram: "الترامواي",
    trTramDesc: "بطاقة سيترام مجانية للطلبة.",
    trSitram: "بطاقة سيترام (مجانية)",
    trSitramDesc: "بطاقة نقل مجانية للطلبة.",
    trInterWilaya: "التنقل بين الولايات",
    trInterWilayaDesc: "حافلات وقطارات نحو مناطق أخرى.",
    trGareRoutiere: "المحطة البرية (الخروبة)",
    trGareRoutiereDesc: "انطلاقات نحو الولايات.",
    trAeroport: "مطار هواري بومدين",
    trAeroportDesc: "رحلات دولية ووطنية.",
    trGareTrain: "محطة القطار",
    trGareTrainDesc: "خطوط SNTF.",
    
    // ============ 7. الإقامة ============
    citeIntro: "الحياة في الإقامة الجامعية.",
    citeGaridi: "إقامة قاريدي",
    citeGaridiDesc: "الأقرب للمدرسة.",
    citeSaid: "إقامة سعيد حمدين",
    citeSaidDesc: "على بعد دقائق بالحافلة.",
    citeRouiba: "إقامة رويسو",
    citeRouibaDesc: "أبعد. تتطلب نقلاً.",
    
    // ============ 8. السباحة ============
    natationIntro: "أين تسبح في الجزائر العاصمة.",
    natPiscine: "مسابح",
    natPiscineDesc: "مسابح عمومية وخاصة.",
    natPlage: "شواطئ",
    natPlageDesc: "شواطئ عمومية.",
    natClub: "أندية السباحة",
    natClubDesc: "أندية للطلاب.",
    
    // ============ 9. الرياضة ============
    sportIntro: "الرياضة الجامعية وخارج الحرم.",
    sportUniv: "الرياضة الجامعية",
    sportUnivDesc: "أنشطة يوفّرها الديوان.",
    sportHors: "رياضة خارج الإقامة",
    sportHorsDesc: "قاعات وأندية خاصة.",
    sportFootball: "كرة القدم",
    sportFootballDesc: "مباريات حرة.",
    sportRunning: "الجري",
    sportRunningDesc: "الجري على الأقدام.",
    sportBasket: "كرة السلة / الطائرة",
    sportBasketDesc: "رياضات جماعية.",
    
    // ============ 10. الأخضر ============
    greenIntro: "المشروع الأخضر وإعادة التدوير.",
    greenRecy: "إعادة تدوير الورق",
    greenRecyDesc: "جمع الورق المستعمل.",
    greenEcologie: "الإيكولوجيا",
    greenEcologieDesc: "مبادرات بيئية.",
    
    // ============ 11. بودكاست ============
    podcastIntro: "بودكاست الطالب ENSTP.",
    podcastEp1: "الحلقة 1",
    podcastEp1Desc: "مرحباً بك في المدرسة.",
    podcastEp2: "الحلقة 2",
    podcastEp2Desc: "الحياة الطلابية.",
    podcastEp3: "الحلقة 3",
    podcastEp3Desc: "نصائح للنجاح.",
    
    // ============ 12. دورات ============
    coursesIntro: "دورات وتكوينات.",
    courseMath: "الرياضيات",
    coursePhysique: "الفيزياء",
    courseInfo: "الإعلام الآلي",
    
    // ============ 13. من نحن ============
    aboutIntro: "مشروع طلابي، 100% مجاني.",
    aboutMission: "مهمتنا",
    aboutMissionDesc: "مساعدة كل طالب جديد على الاندماج.",
    aboutTeam: "فريقنا",
    aboutTeamDesc: "طلاب السنة الأولى مهندس، المجموعة 2، المنشآت القاعدية.",
    aboutValues: "قيمنا",
    aboutValuesDesc: "التضامن، المجانية، الاحترام، الشفافية، الثقة.",
    aboutJoin: "انضم إلى الفريق",
    aboutJoinDesc: "تواصل معنا عبر المجموعة الرسمية.",
    
    // ============ 14. Cartographie ============
    mapIntro: "اضغط على مكان لرؤية اسمه.",
    mapPlaces: "الأماكن"
  },
  
  en: {
    // ============ General ============
    appName: "ENSTP Survival Guide",
    tagline: "Your first day, in your pocket.",
    back: "← Back",
    home: "🏠 Home",
    search: "🔎 Search…",
    noResult: "No results",
    tryOther: "Try another word",
    suggestions: "💡 Try:",
    viewMap: "📍 View on Maps",
    viewVideo: "🎥 Watch video",
    comingSoon: "Coming soon",
    toComplete: "To complete",
    qrTitle: "📱 QR Code",
    qrScan: "Scan this QR code",
    close: "Close",
    loading: "Loading…",
    
    // ============ Home ============
    welcomeTitle: "Welcome",
    welcomeSubtitle: "Everything you need for your first day at ENSTP.",
    startBtn: "Start",
    installBtn: "Install app",
    
    // ============ Sections ============
    sectionEcole: "My school",
    sectionProfs: "My teachers",
    sectionAdmin: "My administration",
    sectionServices: "Services",
    sectionShopping: "Shopping & food",
    sectionTransport: "Transport",
    sectionCite: "Student residence",
    sectionNatation: "Swimming in Algiers",
    sectionSport: "Sport",
    sectionGreen: "Green project",
    sectionPodcast: "Student podcast",
    sectionCourses: "Courses",
    sectionAbout: "Who we are",
    sectionMap: "School map",
    
    // ============ 1. My school ============
    ecoleIntro: "All school places: rooms, amphis, labs, services.",
    ecoleSalle: "Where is my room?",
    ecoleSalleDesc: "26 TD rooms numbered 1 to 26, on several floors.",
    ecoleAmphi: "Amphitheaters A and B",
    ecoleAmphiDesc: "Two large amphitheaters for lectures.",
    ecoleResto: "University restaurant",
    ecoleRestoDesc: "Student-rate meals, 3 times a day.",
    ecoleFoyer: "Foyer",
    ecoleFoyerDesc: "Relaxation and meeting space for students.",
    ecoleDept: "Departments",
    ecoleDeptPrep: "Preparatory cycle",
    ecoleDeptMat: "Materials & Structures",
    ecoleDeptInf: "Infrastructures de Base",
    ecoleLabs: "Laboratories",
    ecoleLabPhysique: "Physics Lab",
    ecoleLabChimie: "Chemistry Lab",
    ecoleLabMeca: "Fluid Mechanics Lab",
    ecoleLabElec: "Electricity Lab",
    ecoleMedecin: "School doctor",
    ecoleMedecinDesc: "Infirmary — first aid.",
    ecoleSécu: "Social security office",
    ecoleSécuDesc: "Affiliation and reimbursements.",
    ecoleEntrepreneuriat: "Entrepreneurship center",
    ecoleEntrepreneuriatDesc: "Support to create your own project.",
    ecoleBiblio: "Library",
    ecoleBiblioDesc: "Reading rooms and book lending.",
    ecoleCite: "Student residence center",
    ecoleCiteDesc: "Management of university residences.",
    
    // ============ 2. Teachers ============
    profsIntro: "Search by subject or name.",
    profPhysique: "Physics",
    profChimie: "Chemistry",
    profAlgebre: "Algebra",
    profAnalyse: "Analysis",
    profStats: "Statistics",
    profFrancais: "French",
    profAnglais: "English",
    profEco: "Economics",
    profGestion: "Management",
    profInfo: "Computer Science",
    
    // ============ 3. Administration ============
    adminIntro: "Administrative offices and contacts.",
    adminDirection: "Direction",
    adminScolarite: "Student Affairs",
    adminDept: "Department secretaries",
    adminRH: "Human Resources",
    adminFinances: "Finance",
    
    // ============ 4. Services ============
    servicesIntro: "All administrative procedures.",
    srvStage: "Internship agreement",
    srvStageDesc: "Procedures to get an internship agreement.",
    srvSecu: "Social security",
    srvSecuDesc: "Registration and follow-up.",
    srvBiblio: "Library membership",
    srvBiblioDesc: "Free registration with student card + photo.",
    srvClub: "Join a club",
    srvClubDesc: "Sport, culture, art…",
    srvIqra: "Iqra platform",
    srvIqraDesc: "Access to the digital reading platform.",
    srvAbsence: "Absence justification",
    srvAbsenceDesc: "Submit a medical document within 3 days.",
    srvCarte: "Student card",
    srvCarteDesc: "Issued after final enrollment.",
    srvCartePerdue: "I lost my card",
    srvCartePerdueDesc: "Loss report + 2 photos.",
    srv
